spring:
  application:
    name: minipay

  datasource:
    master:
      jdbcUrl: jdbc:mysql://localhost:3307/minipay?serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: masterpw
    slave:
      jdbcUrl: jdbc:mysql://localhost:3308/minipay?serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: slavepw
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
